"""add pageview stats

Revision ID: 3df282c597f4
Revises: ea92eaba66c4
Create Date: 2026-07-11 17:59:35.915319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 字段类型（AutoString 等）在迁移脚本里的渲染依赖


# revision identifiers, used by Alembic.
revision: str = '3df282c597f4'
down_revision: Union[str, Sequence[str], None] = 'ea92eaba66c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pageview',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visitor_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('pageview', schema=None) as batch_op:
        batch_op.create_index('ix_pageview_album', ['album_id'], unique=False)
        batch_op.create_index('ix_pageview_kind_created', ['kind', 'created_at'], unique=False)
        batch_op.create_index('ix_pageview_post', ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pageview_visitor_key'), ['visitor_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pageview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pageview_visitor_key'))
        batch_op.drop_index('ix_pageview_post')
        batch_op.drop_index('ix_pageview_kind_created')
        batch_op.drop_index('ix_pageview_album')

    op.drop_table('pageview')
    # ### end Alembic commands ###
