"""add_trip_tables

Revision ID: 717a55282007
Revises: 3df282c597f4
Create Date: 2026-07-15 21:51:38.537710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 字段类型（AutoString 等）在迁移脚本里的渲染依赖


# revision identifiers, used by Alembic.
revision: str = '717a55282007'
down_revision: Union[str, Sequence[str], None] = '3df282c597f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_media_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('trippoint',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('point_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('location_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('polyline_to_next', sa.Text(), nullable=True),
    sa.Column('distance_to_next', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trippoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trippoint_trip_id'), ['trip_id'], unique=False)

    op.create_table('trippointmedia',
    sa.Column('point_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point_id'], ['trippoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('point_id', 'media_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trippointmedia')
    with op.batch_alter_table('trippoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trippoint_trip_id'))

    op.drop_table('trippoint')
    op.drop_table('trip')
    # ### end Alembic commands ###
