"""add trip ai recommendation fields

Revision ID: b4f78437d990
Revises: 717a55282007
Create Date: 2026-08-15 22:43:07.327555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 字段类型（AutoString 等）在迁移脚本里的渲染依赖


# revision identifiers, used by Alembic.
revision: str = 'b4f78437d990'
down_revision: Union[str, Sequence[str], None] = '717a55282007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_mode', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False, server_default='motorcycle'))
        batch_op.add_column(sa.Column('route_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interest_tags', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.Text(), nullable=True))

    with op.batch_alter_table('trippoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_rec_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('ai_rec', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trippoint', schema=None) as batch_op:
        batch_op.drop_column('ai_rec')
        batch_op.drop_column('ai_rec_status')

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('interest_tags')
        batch_op.drop_column('route_plan')
        batch_op.drop_column('trip_mode')

    # ### end Alembic commands ###
