"""drop trippointmedia table

Revision ID: d73fdccb226f
Revises: b4f78437d990
Create Date: 2026-08-18 21:27:19.579976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 字段类型（AutoString 等）在迁移脚本里的渲染依赖


# revision identifiers, used by Alembic.
revision: str = 'd73fdccb226f'
down_revision: Union[str, Sequence[str], None] = 'b4f78437d990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trippointmedia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trippointmedia',
    sa.Column('point_id', sa.VARCHAR(), nullable=False),
    sa.Column('media_id', sa.VARCHAR(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point_id'], ['trippoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('point_id', 'media_id')
    )
    # ### end Alembic commands ###
